#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <directory>"
    exit 1
fi

directory="$1"

convert_function_names() {
    file_path="$1"
    
    sed -nE 's/function ([A-Z][a-zA-Z0-9]+)[\s\(].*/\1/p' "$file_path" | while read -r function_name; do
        snake_case_name=""
        prev_char=""

        for (( i=0; i<${#function_name}; i++ )); do
            char="${function_name:$i:1}"
            if [[ $char =~ [A-Z] && $prev_char =~ [a-z] ]]; then
                snake_case_name="${snake_case_name}_"
            fi

            char_lower=$(echo "$char" | tr 'A-Z' 'a-z')
            snake_case_name="${snake_case_name}$char_lower"
            prev_char=$char
        done

        echo "$file_path: $function_name -> $snake_case_name"
        sed -E -i '' "s/function $function_name\(/function $snake_case_name\(/" "$file_path"
    done
}

export -f convert_function_names

find "$directory" -name '*.php' | xargs -I {} -P 4 bash -c 'convert_function_names "$@"' _ {}
