#!/usr/bin/env bash

# This script will merge the current branch into the release/dev branch
# and then switch back to the current branch.

# Save as merge-dev in your path (ex. ~/bin/merge-dev) and make executable

set -e

# ask for confirmation
read -p "Are you sure you want to merge into release/dev? (y/n) " -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    echo
    exit 1
fi

# set up colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

CURRENT_BRANCH=$( git rev-parse --abbrev-ref HEAD )
echo $CURRENT_BRANCH
git checkout release/dev
git pull
git merge $CURRENT_BRANCH
if [ $? -ne 0 ]; then
    printf " :: ${RED}Error:${NC} Merge failed. Exiting \n"
    exit 1
else
    printf " :: ${GREEN}Merge successful${NC} \n"
    git push
fi
git checkout $CURRENT_BRANCH